MODEL: 'CNN5d'

DATASET: 
  LOOKBACK_WIN: 5
  START_DATE: 20151231
  END_DATE: 20171231
  MODE: default
  INDICATORS: 
    - NAME: MA
    - PARAM: 5 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET20
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I5R20/I5R20_15-17.tar
  LOG_SAVE_FILE: logs/I5R20/I5R20_15-17.csv
  EARLY_STOP_EPOCH: 4

TEST:
  START_DATE: 20171231
  END_DATE: 20181231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I5R20/I5R20_17-18.csv