MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 20131231
  END_DATE: 20151231
  MODE: default
  INDICATORS: 
    - NAME: MA
    - PARAM: 20 # using data augmentation
  SHOW_VOLUME: True # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET20
  VALID_RATIO: 0.3
  BATCH_SIZE: 128
  NEPOCH: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I20R20/I20R20_13-15.tar
  LOG_SAVE_FILE: logs/I20R20/I20R20_13-15.csv
  EARLY_STOP_EPOCH: 4

TEST:
  START_DATE: 20151231
  END_DATE: 20161231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I20R20/I20R20_15-16.csv