MODEL: 'CNN20d'

DATASET: 
  LOOKBACK_WIN: 20
  START_DATE: 20091231
  END_DATE: 20111231
  INDICATORS: 
    # - NAME: MA
    # - PARAM: 20 # using data augmentation
  SHOW_VOLUME: False # using data augmentation
  SAMPLE_RATE: 0.2
  PARALLEL_NUM: 32

TRAIN:
  LABEL: RET5
  VALID_RATIO: 0.3
  # BATCH_SIZE: 128
  BATCH_SIZE: 64
  NEPOCH: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.01
  MODEL_SAVE_FILE: models/I20R5_OHLC/I20R5_OHLC_09-11.tar
  LOG_SAVE_FILE: logs/I20R5_OHLC/I20R5_OHLC_09-11.csv
  EARLY_STOP_EPOCH: 4

TEST:
  START_DATE: 20111231
  END_DATE: 20121231

INFERENCE:
  FACTORS_SAVE_FILE: factors/I20R5_OHLC/I20R5_OHLC_11-12.csv